using System;

namespace Shared.Interops
{
	public enum SPNotificationType : uint
	{
		SP_NOTIFICATION_GENERAL_ERROR = 1U,
		SP_NOTIFICATION_SP_INITIALIZED,
		SP_NOTIFICATION_SP_INIT_ERROR = 4U,
		SP_NOTIFICATION_IN_START_FAILED = 256U,
		SP_NOTIFICATION_IN_DISCONNECTED = 512U,
		SP_NOTIFICATION_IN_STARTED = 768U,
		SP_NOTIFICATION_IN_STOPPED = 1024U,
		SP_NOTIFICATION_IN_MISSING = 1280U,
		SP_NOTIFICATION_IN_STARTING = 1536U,
		SP_NOTIFICATION_IN_RESETTING = 1792U,
		SP_NOTIFICATION_IN_DUCKED = 2048U,
		SP_NOTIFICATION_IN_STATS = 2304U,
		SP_NOTIFICATION_OUT_START_FAILED = 65536U,
		SP_NOTIFICATION_OUT_DISCONNECTED = 131072U,
		SP_NOTIFICATION_OUT_STARTED = 196608U,
		SP_NOTIFICATION_OUT_STOPPED = 262144U,
		SP_NOTIFICATION_OUT_MISSING = 327680U,
		SP_NOTIFICATION_OUT_STARTING = 393216U,
		SP_NOTIFICATION_OUT_RESETTING = 458752U,
		SP_NOTIFICATION_OUT_DUCKED = 524288U,
		SP_NOTIFICATION_OUT_STATS = 589824U
	}
}
