using System;

namespace Shared.Interops.IMMDeviceAPI
{
	[Flags]
	public enum ENDPOINT_HARDWARE_SUPPORT_XXX
	{
		ENDPOINT_HARDWARE_SUPPORT_VOLUME = 1,
		ENDPOINT_HARDWARE_SUPPORT_MUTE = 2,
		ENDPOINT_HARDWARE_SUPPORT_METER = 4
	}
}
